---
abstract: 'modules used by JMATES (for work)'
author:
  - 'Jeremy Mates <jmates@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.64, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-BeLike-JMATES-WorkWorkWork
no_index:
  directory:
    - t
    - inc
requires:
  App::cpanminus: 0
  Capture::Tiny: 0
  Data::Dumper::Concise: 0
  File::AtomicWrite: 0
  File::Cmp: 0
  File::HomeDir: 0
  File::Path::Tiny: 0
  File::Tail: 0
  IO::Socket::INET6: 0
  IPC::System::Simple: 0
  JSON: 0
  LWP::Protocol::https: 0
  LWP::UserAgent: 0
  Net::DNS: 0
  Net::LDAP: 0
  Net::Ping: 0
  Perl::Tidy: 0
  Term::CallEditor: 0
  Term::ReadKey: 0
  Term::ReadLine::Gnu: 0
  Text::Autoformat: 0
  Time::HiRes: 0
  URI: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
  perl: 5.01
resources:
  homepage: http://github.com/thrig/Task-BeLike-JMATES-WorkWorkWork
  license: http://dev.perl.org/licenses/
  repository: http://github.com/thrig/Task-BeLike-JMATES-WorkWorkWork
version: 0.02
